name: Build

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Debug Event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --debug
        
      - name: Get commit hash
        id: hash
        run: |
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "Current commit hash: $(git rev-parse --short HEAD)"
          git branch --show-current
          git status
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EEE-${{ steps.hash.outputs.hash }}
          path: target/eee-*.jar
          retention-days: 90
        
      - name: List files in target directory
        run: ls -la target/ 