name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/eee-*.jar
          generate_release_notes: true 